package com.sy.modules.entity.ws;

import java.io.Serializable;
import java.util.Date;

public class WsFanFei implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ws_fanfei.f_id
     *
     * @mbggenerated
     */
    private Integer fId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ws_fanfei.f_name
     *
     * @mbggenerated
     */
    private String fName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ws_fanfei.f_remark
     *
     * @mbggenerated
     */
    private String fRemark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ws_fanfei.f_money
     *
     * @mbggenerated
     */
    private String fMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ws_fanfei.f_pic
     *
     * @mbggenerated
     */
    private String fPic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ws_fanfei.f_type
     *
     * @mbggenerated
     */
    private Byte fType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ws_fanfei.del_status
     *
     * @mbggenerated
     */
    private Byte delStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ws_fanfei.create_name
     *
     * @mbggenerated
     */
    private String createName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ws_fanfei.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ws_fanfei.update_name
     *
     * @mbggenerated
     */
    private String updateName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ws_fanfei.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ws_fanfei
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ws_fanfei.f_id
     *
     * @return the value of ws_fanfei.f_id
     *
     * @mbggenerated
     */
    public Integer getfId() {
        return fId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ws_fanfei.f_id
     *
     * @param fId the value for ws_fanfei.f_id
     *
     * @mbggenerated
     */
    public void setfId(Integer fId) {
        this.fId = fId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ws_fanfei.f_name
     *
     * @return the value of ws_fanfei.f_name
     *
     * @mbggenerated
     */
    public String getfName() {
        return fName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ws_fanfei.f_name
     *
     * @param fName the value for ws_fanfei.f_name
     *
     * @mbggenerated
     */
    public void setfName(String fName) {
        this.fName = fName == null ? null : fName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ws_fanfei.f_remark
     *
     * @return the value of ws_fanfei.f_remark
     *
     * @mbggenerated
     */
    public String getfRemark() {
        return fRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ws_fanfei.f_remark
     *
     * @param fRemark the value for ws_fanfei.f_remark
     *
     * @mbggenerated
     */
    public void setfRemark(String fRemark) {
        this.fRemark = fRemark == null ? null : fRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ws_fanfei.f_money
     *
     * @return the value of ws_fanfei.f_money
     *
     * @mbggenerated
     */
    public String getfMoney() {
        return fMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ws_fanfei.f_money
     *
     * @param fMoney the value for ws_fanfei.f_money
     *
     * @mbggenerated
     */
    public void setfMoney(String fMoney) {
        this.fMoney = fMoney == null ? null : fMoney.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ws_fanfei.f_pic
     *
     * @return the value of ws_fanfei.f_pic
     *
     * @mbggenerated
     */
    public String getfPic() {
        return fPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ws_fanfei.f_pic
     *
     * @param fPic the value for ws_fanfei.f_pic
     *
     * @mbggenerated
     */
    public void setfPic(String fPic) {
        this.fPic = fPic == null ? null : fPic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ws_fanfei.f_type
     *
     * @return the value of ws_fanfei.f_type
     *
     * @mbggenerated
     */
    public Byte getfType() {
        return fType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ws_fanfei.f_type
     *
     * @param fType the value for ws_fanfei.f_type
     *
     * @mbggenerated
     */
    public void setfType(Byte fType) {
        this.fType = fType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ws_fanfei.del_status
     *
     * @return the value of ws_fanfei.del_status
     *
     * @mbggenerated
     */
    public Byte getDelStatus() {
        return delStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ws_fanfei.del_status
     *
     * @param delStatus the value for ws_fanfei.del_status
     *
     * @mbggenerated
     */
    public void setDelStatus(Byte delStatus) {
        this.delStatus = delStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ws_fanfei.create_name
     *
     * @return the value of ws_fanfei.create_name
     *
     * @mbggenerated
     */
    public String getCreateName() {
        return createName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ws_fanfei.create_name
     *
     * @param createName the value for ws_fanfei.create_name
     *
     * @mbggenerated
     */
    public void setCreateName(String createName) {
        this.createName = createName == null ? null : createName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ws_fanfei.create_time
     *
     * @return the value of ws_fanfei.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ws_fanfei.create_time
     *
     * @param createTime the value for ws_fanfei.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ws_fanfei.update_name
     *
     * @return the value of ws_fanfei.update_name
     *
     * @mbggenerated
     */
    public String getUpdateName() {
        return updateName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ws_fanfei.update_name
     *
     * @param updateName the value for ws_fanfei.update_name
     *
     * @mbggenerated
     */
    public void setUpdateName(String updateName) {
        this.updateName = updateName == null ? null : updateName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ws_fanfei.update_time
     *
     * @return the value of ws_fanfei.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ws_fanfei.update_time
     *
     * @param updateTime the value for ws_fanfei.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}