package com.sy.modules.entity.ws;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class WsHumanExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ws_human
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ws_human
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ws_human
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ws_human
     *
     * @mbggenerated
     */
    public WsHumanExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ws_human
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ws_human
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ws_human
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ws_human
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ws_human
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ws_human
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ws_human
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ws_human
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ws_human
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ws_human
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ws_human
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andHumanIdIsNull() {
            addCriterion("human_id is null");
            return (Criteria) this;
        }

        public Criteria andHumanIdIsNotNull() {
            addCriterion("human_id is not null");
            return (Criteria) this;
        }

        public Criteria andHumanIdEqualTo(Long value) {
            addCriterion("human_id =", value, "humanId");
            return (Criteria) this;
        }

        public Criteria andHumanIdNotEqualTo(Long value) {
            addCriterion("human_id <>", value, "humanId");
            return (Criteria) this;
        }

        public Criteria andHumanIdGreaterThan(Long value) {
            addCriterion("human_id >", value, "humanId");
            return (Criteria) this;
        }

        public Criteria andHumanIdGreaterThanOrEqualTo(Long value) {
            addCriterion("human_id >=", value, "humanId");
            return (Criteria) this;
        }

        public Criteria andHumanIdLessThan(Long value) {
            addCriterion("human_id <", value, "humanId");
            return (Criteria) this;
        }

        public Criteria andHumanIdLessThanOrEqualTo(Long value) {
            addCriterion("human_id <=", value, "humanId");
            return (Criteria) this;
        }

        public Criteria andHumanIdIn(List<Long> values) {
            addCriterion("human_id in", values, "humanId");
            return (Criteria) this;
        }

        public Criteria andHumanIdNotIn(List<Long> values) {
            addCriterion("human_id not in", values, "humanId");
            return (Criteria) this;
        }

        public Criteria andHumanIdBetween(Long value1, Long value2) {
            addCriterion("human_id between", value1, value2, "humanId");
            return (Criteria) this;
        }

        public Criteria andHumanIdNotBetween(Long value1, Long value2) {
            addCriterion("human_id not between", value1, value2, "humanId");
            return (Criteria) this;
        }

        public Criteria andHumanAccountIsNull() {
            addCriterion("human_account is null");
            return (Criteria) this;
        }

        public Criteria andHumanAccountIsNotNull() {
            addCriterion("human_account is not null");
            return (Criteria) this;
        }

        public Criteria andHumanAccountEqualTo(String value) {
            addCriterion("human_account =", value, "humanAccount");
            return (Criteria) this;
        }

        public Criteria andHumanAccountNotEqualTo(String value) {
            addCriterion("human_account <>", value, "humanAccount");
            return (Criteria) this;
        }

        public Criteria andHumanAccountGreaterThan(String value) {
            addCriterion("human_account >", value, "humanAccount");
            return (Criteria) this;
        }

        public Criteria andHumanAccountGreaterThanOrEqualTo(String value) {
            addCriterion("human_account >=", value, "humanAccount");
            return (Criteria) this;
        }

        public Criteria andHumanAccountLessThan(String value) {
            addCriterion("human_account <", value, "humanAccount");
            return (Criteria) this;
        }

        public Criteria andHumanAccountLessThanOrEqualTo(String value) {
            addCriterion("human_account <=", value, "humanAccount");
            return (Criteria) this;
        }

        public Criteria andHumanAccountLike(String value) {
            addCriterion("human_account like", value, "humanAccount");
            return (Criteria) this;
        }

        public Criteria andHumanAccountNotLike(String value) {
            addCriterion("human_account not like", value, "humanAccount");
            return (Criteria) this;
        }

        public Criteria andHumanAccountIn(List<String> values) {
            addCriterion("human_account in", values, "humanAccount");
            return (Criteria) this;
        }

        public Criteria andHumanAccountNotIn(List<String> values) {
            addCriterion("human_account not in", values, "humanAccount");
            return (Criteria) this;
        }

        public Criteria andHumanAccountBetween(String value1, String value2) {
            addCriterion("human_account between", value1, value2, "humanAccount");
            return (Criteria) this;
        }

        public Criteria andHumanAccountNotBetween(String value1, String value2) {
            addCriterion("human_account not between", value1, value2, "humanAccount");
            return (Criteria) this;
        }

        public Criteria andHumanPasswordIsNull() {
            addCriterion("human_password is null");
            return (Criteria) this;
        }

        public Criteria andHumanPasswordIsNotNull() {
            addCriterion("human_password is not null");
            return (Criteria) this;
        }

        public Criteria andHumanPasswordEqualTo(String value) {
            addCriterion("human_password =", value, "humanPassword");
            return (Criteria) this;
        }

        public Criteria andHumanPasswordNotEqualTo(String value) {
            addCriterion("human_password <>", value, "humanPassword");
            return (Criteria) this;
        }

        public Criteria andHumanPasswordGreaterThan(String value) {
            addCriterion("human_password >", value, "humanPassword");
            return (Criteria) this;
        }

        public Criteria andHumanPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("human_password >=", value, "humanPassword");
            return (Criteria) this;
        }

        public Criteria andHumanPasswordLessThan(String value) {
            addCriterion("human_password <", value, "humanPassword");
            return (Criteria) this;
        }

        public Criteria andHumanPasswordLessThanOrEqualTo(String value) {
            addCriterion("human_password <=", value, "humanPassword");
            return (Criteria) this;
        }

        public Criteria andHumanPasswordLike(String value) {
            addCriterion("human_password like", value, "humanPassword");
            return (Criteria) this;
        }

        public Criteria andHumanPasswordNotLike(String value) {
            addCriterion("human_password not like", value, "humanPassword");
            return (Criteria) this;
        }

        public Criteria andHumanPasswordIn(List<String> values) {
            addCriterion("human_password in", values, "humanPassword");
            return (Criteria) this;
        }

        public Criteria andHumanPasswordNotIn(List<String> values) {
            addCriterion("human_password not in", values, "humanPassword");
            return (Criteria) this;
        }

        public Criteria andHumanPasswordBetween(String value1, String value2) {
            addCriterion("human_password between", value1, value2, "humanPassword");
            return (Criteria) this;
        }

        public Criteria andHumanPasswordNotBetween(String value1, String value2) {
            addCriterion("human_password not between", value1, value2, "humanPassword");
            return (Criteria) this;
        }

        public Criteria andHumanQuestionIsNull() {
            addCriterion("human_question is null");
            return (Criteria) this;
        }

        public Criteria andHumanQuestionIsNotNull() {
            addCriterion("human_question is not null");
            return (Criteria) this;
        }

        public Criteria andHumanQuestionEqualTo(String value) {
            addCriterion("human_question =", value, "humanQuestion");
            return (Criteria) this;
        }

        public Criteria andHumanQuestionNotEqualTo(String value) {
            addCriterion("human_question <>", value, "humanQuestion");
            return (Criteria) this;
        }

        public Criteria andHumanQuestionGreaterThan(String value) {
            addCriterion("human_question >", value, "humanQuestion");
            return (Criteria) this;
        }

        public Criteria andHumanQuestionGreaterThanOrEqualTo(String value) {
            addCriterion("human_question >=", value, "humanQuestion");
            return (Criteria) this;
        }

        public Criteria andHumanQuestionLessThan(String value) {
            addCriterion("human_question <", value, "humanQuestion");
            return (Criteria) this;
        }

        public Criteria andHumanQuestionLessThanOrEqualTo(String value) {
            addCriterion("human_question <=", value, "humanQuestion");
            return (Criteria) this;
        }

        public Criteria andHumanQuestionLike(String value) {
            addCriterion("human_question like", value, "humanQuestion");
            return (Criteria) this;
        }

        public Criteria andHumanQuestionNotLike(String value) {
            addCriterion("human_question not like", value, "humanQuestion");
            return (Criteria) this;
        }

        public Criteria andHumanQuestionIn(List<String> values) {
            addCriterion("human_question in", values, "humanQuestion");
            return (Criteria) this;
        }

        public Criteria andHumanQuestionNotIn(List<String> values) {
            addCriterion("human_question not in", values, "humanQuestion");
            return (Criteria) this;
        }

        public Criteria andHumanQuestionBetween(String value1, String value2) {
            addCriterion("human_question between", value1, value2, "humanQuestion");
            return (Criteria) this;
        }

        public Criteria andHumanQuestionNotBetween(String value1, String value2) {
            addCriterion("human_question not between", value1, value2, "humanQuestion");
            return (Criteria) this;
        }

        public Criteria andHumanAnswerIsNull() {
            addCriterion("human_answer is null");
            return (Criteria) this;
        }

        public Criteria andHumanAnswerIsNotNull() {
            addCriterion("human_answer is not null");
            return (Criteria) this;
        }

        public Criteria andHumanAnswerEqualTo(String value) {
            addCriterion("human_answer =", value, "humanAnswer");
            return (Criteria) this;
        }

        public Criteria andHumanAnswerNotEqualTo(String value) {
            addCriterion("human_answer <>", value, "humanAnswer");
            return (Criteria) this;
        }

        public Criteria andHumanAnswerGreaterThan(String value) {
            addCriterion("human_answer >", value, "humanAnswer");
            return (Criteria) this;
        }

        public Criteria andHumanAnswerGreaterThanOrEqualTo(String value) {
            addCriterion("human_answer >=", value, "humanAnswer");
            return (Criteria) this;
        }

        public Criteria andHumanAnswerLessThan(String value) {
            addCriterion("human_answer <", value, "humanAnswer");
            return (Criteria) this;
        }

        public Criteria andHumanAnswerLessThanOrEqualTo(String value) {
            addCriterion("human_answer <=", value, "humanAnswer");
            return (Criteria) this;
        }

        public Criteria andHumanAnswerLike(String value) {
            addCriterion("human_answer like", value, "humanAnswer");
            return (Criteria) this;
        }

        public Criteria andHumanAnswerNotLike(String value) {
            addCriterion("human_answer not like", value, "humanAnswer");
            return (Criteria) this;
        }

        public Criteria andHumanAnswerIn(List<String> values) {
            addCriterion("human_answer in", values, "humanAnswer");
            return (Criteria) this;
        }

        public Criteria andHumanAnswerNotIn(List<String> values) {
            addCriterion("human_answer not in", values, "humanAnswer");
            return (Criteria) this;
        }

        public Criteria andHumanAnswerBetween(String value1, String value2) {
            addCriterion("human_answer between", value1, value2, "humanAnswer");
            return (Criteria) this;
        }

        public Criteria andHumanAnswerNotBetween(String value1, String value2) {
            addCriterion("human_answer not between", value1, value2, "humanAnswer");
            return (Criteria) this;
        }

        public Criteria andHumanPhoneIsNull() {
            addCriterion("human_phone is null");
            return (Criteria) this;
        }

        public Criteria andHumanPhoneIsNotNull() {
            addCriterion("human_phone is not null");
            return (Criteria) this;
        }

        public Criteria andHumanPhoneEqualTo(String value) {
            addCriterion("human_phone =", value, "humanPhone");
            return (Criteria) this;
        }

        public Criteria andHumanPhoneNotEqualTo(String value) {
            addCriterion("human_phone <>", value, "humanPhone");
            return (Criteria) this;
        }

        public Criteria andHumanPhoneGreaterThan(String value) {
            addCriterion("human_phone >", value, "humanPhone");
            return (Criteria) this;
        }

        public Criteria andHumanPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("human_phone >=", value, "humanPhone");
            return (Criteria) this;
        }

        public Criteria andHumanPhoneLessThan(String value) {
            addCriterion("human_phone <", value, "humanPhone");
            return (Criteria) this;
        }

        public Criteria andHumanPhoneLessThanOrEqualTo(String value) {
            addCriterion("human_phone <=", value, "humanPhone");
            return (Criteria) this;
        }

        public Criteria andHumanPhoneLike(String value) {
            addCriterion("human_phone like", value, "humanPhone");
            return (Criteria) this;
        }

        public Criteria andHumanPhoneNotLike(String value) {
            addCriterion("human_phone not like", value, "humanPhone");
            return (Criteria) this;
        }

        public Criteria andHumanPhoneIn(List<String> values) {
            addCriterion("human_phone in", values, "humanPhone");
            return (Criteria) this;
        }

        public Criteria andHumanPhoneNotIn(List<String> values) {
            addCriterion("human_phone not in", values, "humanPhone");
            return (Criteria) this;
        }

        public Criteria andHumanPhoneBetween(String value1, String value2) {
            addCriterion("human_phone between", value1, value2, "humanPhone");
            return (Criteria) this;
        }

        public Criteria andHumanPhoneNotBetween(String value1, String value2) {
            addCriterion("human_phone not between", value1, value2, "humanPhone");
            return (Criteria) this;
        }

        public Criteria andHumanQqIsNull() {
            addCriterion("human_qq is null");
            return (Criteria) this;
        }

        public Criteria andHumanQqIsNotNull() {
            addCriterion("human_qq is not null");
            return (Criteria) this;
        }

        public Criteria andHumanQqEqualTo(String value) {
            addCriterion("human_qq =", value, "humanQq");
            return (Criteria) this;
        }

        public Criteria andHumanQqNotEqualTo(String value) {
            addCriterion("human_qq <>", value, "humanQq");
            return (Criteria) this;
        }

        public Criteria andHumanQqGreaterThan(String value) {
            addCriterion("human_qq >", value, "humanQq");
            return (Criteria) this;
        }

        public Criteria andHumanQqGreaterThanOrEqualTo(String value) {
            addCriterion("human_qq >=", value, "humanQq");
            return (Criteria) this;
        }

        public Criteria andHumanQqLessThan(String value) {
            addCriterion("human_qq <", value, "humanQq");
            return (Criteria) this;
        }

        public Criteria andHumanQqLessThanOrEqualTo(String value) {
            addCriterion("human_qq <=", value, "humanQq");
            return (Criteria) this;
        }

        public Criteria andHumanQqLike(String value) {
            addCriterion("human_qq like", value, "humanQq");
            return (Criteria) this;
        }

        public Criteria andHumanQqNotLike(String value) {
            addCriterion("human_qq not like", value, "humanQq");
            return (Criteria) this;
        }

        public Criteria andHumanQqIn(List<String> values) {
            addCriterion("human_qq in", values, "humanQq");
            return (Criteria) this;
        }

        public Criteria andHumanQqNotIn(List<String> values) {
            addCriterion("human_qq not in", values, "humanQq");
            return (Criteria) this;
        }

        public Criteria andHumanQqBetween(String value1, String value2) {
            addCriterion("human_qq between", value1, value2, "humanQq");
            return (Criteria) this;
        }

        public Criteria andHumanQqNotBetween(String value1, String value2) {
            addCriterion("human_qq not between", value1, value2, "humanQq");
            return (Criteria) this;
        }

        public Criteria andHumanNameIsNull() {
            addCriterion("human_name is null");
            return (Criteria) this;
        }

        public Criteria andHumanNameIsNotNull() {
            addCriterion("human_name is not null");
            return (Criteria) this;
        }

        public Criteria andHumanNameEqualTo(String value) {
            addCriterion("human_name =", value, "humanName");
            return (Criteria) this;
        }

        public Criteria andHumanNameNotEqualTo(String value) {
            addCriterion("human_name <>", value, "humanName");
            return (Criteria) this;
        }

        public Criteria andHumanNameGreaterThan(String value) {
            addCriterion("human_name >", value, "humanName");
            return (Criteria) this;
        }

        public Criteria andHumanNameGreaterThanOrEqualTo(String value) {
            addCriterion("human_name >=", value, "humanName");
            return (Criteria) this;
        }

        public Criteria andHumanNameLessThan(String value) {
            addCriterion("human_name <", value, "humanName");
            return (Criteria) this;
        }

        public Criteria andHumanNameLessThanOrEqualTo(String value) {
            addCriterion("human_name <=", value, "humanName");
            return (Criteria) this;
        }

        public Criteria andHumanNameLike(String value) {
            addCriterion("human_name like", value, "humanName");
            return (Criteria) this;
        }

        public Criteria andHumanNameNotLike(String value) {
            addCriterion("human_name not like", value, "humanName");
            return (Criteria) this;
        }

        public Criteria andHumanNameIn(List<String> values) {
            addCriterion("human_name in", values, "humanName");
            return (Criteria) this;
        }

        public Criteria andHumanNameNotIn(List<String> values) {
            addCriterion("human_name not in", values, "humanName");
            return (Criteria) this;
        }

        public Criteria andHumanNameBetween(String value1, String value2) {
            addCriterion("human_name between", value1, value2, "humanName");
            return (Criteria) this;
        }

        public Criteria andHumanNameNotBetween(String value1, String value2) {
            addCriterion("human_name not between", value1, value2, "humanName");
            return (Criteria) this;
        }

        public Criteria andHumanAddressIsNull() {
            addCriterion("human_address is null");
            return (Criteria) this;
        }

        public Criteria andHumanAddressIsNotNull() {
            addCriterion("human_address is not null");
            return (Criteria) this;
        }

        public Criteria andHumanAddressEqualTo(String value) {
            addCriterion("human_address =", value, "humanAddress");
            return (Criteria) this;
        }

        public Criteria andHumanAddressNotEqualTo(String value) {
            addCriterion("human_address <>", value, "humanAddress");
            return (Criteria) this;
        }

        public Criteria andHumanAddressGreaterThan(String value) {
            addCriterion("human_address >", value, "humanAddress");
            return (Criteria) this;
        }

        public Criteria andHumanAddressGreaterThanOrEqualTo(String value) {
            addCriterion("human_address >=", value, "humanAddress");
            return (Criteria) this;
        }

        public Criteria andHumanAddressLessThan(String value) {
            addCriterion("human_address <", value, "humanAddress");
            return (Criteria) this;
        }

        public Criteria andHumanAddressLessThanOrEqualTo(String value) {
            addCriterion("human_address <=", value, "humanAddress");
            return (Criteria) this;
        }

        public Criteria andHumanAddressLike(String value) {
            addCriterion("human_address like", value, "humanAddress");
            return (Criteria) this;
        }

        public Criteria andHumanAddressNotLike(String value) {
            addCriterion("human_address not like", value, "humanAddress");
            return (Criteria) this;
        }

        public Criteria andHumanAddressIn(List<String> values) {
            addCriterion("human_address in", values, "humanAddress");
            return (Criteria) this;
        }

        public Criteria andHumanAddressNotIn(List<String> values) {
            addCriterion("human_address not in", values, "humanAddress");
            return (Criteria) this;
        }

        public Criteria andHumanAddressBetween(String value1, String value2) {
            addCriterion("human_address between", value1, value2, "humanAddress");
            return (Criteria) this;
        }

        public Criteria andHumanAddressNotBetween(String value1, String value2) {
            addCriterion("human_address not between", value1, value2, "humanAddress");
            return (Criteria) this;
        }

        public Criteria andDelStatueIsNull() {
            addCriterion("del_statue is null");
            return (Criteria) this;
        }

        public Criteria andDelStatueIsNotNull() {
            addCriterion("del_statue is not null");
            return (Criteria) this;
        }

        public Criteria andDelStatueEqualTo(Byte value) {
            addCriterion("del_statue =", value, "delStatue");
            return (Criteria) this;
        }

        public Criteria andDelStatueNotEqualTo(Byte value) {
            addCriterion("del_statue <>", value, "delStatue");
            return (Criteria) this;
        }

        public Criteria andDelStatueGreaterThan(Byte value) {
            addCriterion("del_statue >", value, "delStatue");
            return (Criteria) this;
        }

        public Criteria andDelStatueGreaterThanOrEqualTo(Byte value) {
            addCriterion("del_statue >=", value, "delStatue");
            return (Criteria) this;
        }

        public Criteria andDelStatueLessThan(Byte value) {
            addCriterion("del_statue <", value, "delStatue");
            return (Criteria) this;
        }

        public Criteria andDelStatueLessThanOrEqualTo(Byte value) {
            addCriterion("del_statue <=", value, "delStatue");
            return (Criteria) this;
        }

        public Criteria andDelStatueIn(List<Byte> values) {
            addCriterion("del_statue in", values, "delStatue");
            return (Criteria) this;
        }

        public Criteria andDelStatueNotIn(List<Byte> values) {
            addCriterion("del_statue not in", values, "delStatue");
            return (Criteria) this;
        }

        public Criteria andDelStatueBetween(Byte value1, Byte value2) {
            addCriterion("del_statue between", value1, value2, "delStatue");
            return (Criteria) this;
        }

        public Criteria andDelStatueNotBetween(Byte value1, Byte value2) {
            addCriterion("del_statue not between", value1, value2, "delStatue");
            return (Criteria) this;
        }

        public Criteria andCreateNameIsNull() {
            addCriterion("create_name is null");
            return (Criteria) this;
        }

        public Criteria andCreateNameIsNotNull() {
            addCriterion("create_name is not null");
            return (Criteria) this;
        }

        public Criteria andCreateNameEqualTo(String value) {
            addCriterion("create_name =", value, "createName");
            return (Criteria) this;
        }

        public Criteria andCreateNameNotEqualTo(String value) {
            addCriterion("create_name <>", value, "createName");
            return (Criteria) this;
        }

        public Criteria andCreateNameGreaterThan(String value) {
            addCriterion("create_name >", value, "createName");
            return (Criteria) this;
        }

        public Criteria andCreateNameGreaterThanOrEqualTo(String value) {
            addCriterion("create_name >=", value, "createName");
            return (Criteria) this;
        }

        public Criteria andCreateNameLessThan(String value) {
            addCriterion("create_name <", value, "createName");
            return (Criteria) this;
        }

        public Criteria andCreateNameLessThanOrEqualTo(String value) {
            addCriterion("create_name <=", value, "createName");
            return (Criteria) this;
        }

        public Criteria andCreateNameLike(String value) {
            addCriterion("create_name like", value, "createName");
            return (Criteria) this;
        }

        public Criteria andCreateNameNotLike(String value) {
            addCriterion("create_name not like", value, "createName");
            return (Criteria) this;
        }

        public Criteria andCreateNameIn(List<String> values) {
            addCriterion("create_name in", values, "createName");
            return (Criteria) this;
        }

        public Criteria andCreateNameNotIn(List<String> values) {
            addCriterion("create_name not in", values, "createName");
            return (Criteria) this;
        }

        public Criteria andCreateNameBetween(String value1, String value2) {
            addCriterion("create_name between", value1, value2, "createName");
            return (Criteria) this;
        }

        public Criteria andCreateNameNotBetween(String value1, String value2) {
            addCriterion("create_name not between", value1, value2, "createName");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateNameIsNull() {
            addCriterion("update_name is null");
            return (Criteria) this;
        }

        public Criteria andUpdateNameIsNotNull() {
            addCriterion("update_name is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateNameEqualTo(String value) {
            addCriterion("update_name =", value, "updateName");
            return (Criteria) this;
        }

        public Criteria andUpdateNameNotEqualTo(String value) {
            addCriterion("update_name <>", value, "updateName");
            return (Criteria) this;
        }

        public Criteria andUpdateNameGreaterThan(String value) {
            addCriterion("update_name >", value, "updateName");
            return (Criteria) this;
        }

        public Criteria andUpdateNameGreaterThanOrEqualTo(String value) {
            addCriterion("update_name >=", value, "updateName");
            return (Criteria) this;
        }

        public Criteria andUpdateNameLessThan(String value) {
            addCriterion("update_name <", value, "updateName");
            return (Criteria) this;
        }

        public Criteria andUpdateNameLessThanOrEqualTo(String value) {
            addCriterion("update_name <=", value, "updateName");
            return (Criteria) this;
        }

        public Criteria andUpdateNameLike(String value) {
            addCriterion("update_name like", value, "updateName");
            return (Criteria) this;
        }

        public Criteria andUpdateNameNotLike(String value) {
            addCriterion("update_name not like", value, "updateName");
            return (Criteria) this;
        }

        public Criteria andUpdateNameIn(List<String> values) {
            addCriterion("update_name in", values, "updateName");
            return (Criteria) this;
        }

        public Criteria andUpdateNameNotIn(List<String> values) {
            addCriterion("update_name not in", values, "updateName");
            return (Criteria) this;
        }

        public Criteria andUpdateNameBetween(String value1, String value2) {
            addCriterion("update_name between", value1, value2, "updateName");
            return (Criteria) this;
        }

        public Criteria andUpdateNameNotBetween(String value1, String value2) {
            addCriterion("update_name not between", value1, value2, "updateName");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andHumanSexIsNull() {
            addCriterion("human_sex is null");
            return (Criteria) this;
        }

        public Criteria andHumanSexIsNotNull() {
            addCriterion("human_sex is not null");
            return (Criteria) this;
        }

        public Criteria andHumanSexEqualTo(String value) {
            addCriterion("human_sex =", value, "humanSex");
            return (Criteria) this;
        }

        public Criteria andHumanSexNotEqualTo(String value) {
            addCriterion("human_sex <>", value, "humanSex");
            return (Criteria) this;
        }

        public Criteria andHumanSexGreaterThan(String value) {
            addCriterion("human_sex >", value, "humanSex");
            return (Criteria) this;
        }

        public Criteria andHumanSexGreaterThanOrEqualTo(String value) {
            addCriterion("human_sex >=", value, "humanSex");
            return (Criteria) this;
        }

        public Criteria andHumanSexLessThan(String value) {
            addCriterion("human_sex <", value, "humanSex");
            return (Criteria) this;
        }

        public Criteria andHumanSexLessThanOrEqualTo(String value) {
            addCriterion("human_sex <=", value, "humanSex");
            return (Criteria) this;
        }

        public Criteria andHumanSexLike(String value) {
            addCriterion("human_sex like", value, "humanSex");
            return (Criteria) this;
        }

        public Criteria andHumanSexNotLike(String value) {
            addCriterion("human_sex not like", value, "humanSex");
            return (Criteria) this;
        }

        public Criteria andHumanSexIn(List<String> values) {
            addCriterion("human_sex in", values, "humanSex");
            return (Criteria) this;
        }

        public Criteria andHumanSexNotIn(List<String> values) {
            addCriterion("human_sex not in", values, "humanSex");
            return (Criteria) this;
        }

        public Criteria andHumanSexBetween(String value1, String value2) {
            addCriterion("human_sex between", value1, value2, "humanSex");
            return (Criteria) this;
        }

        public Criteria andHumanSexNotBetween(String value1, String value2) {
            addCriterion("human_sex not between", value1, value2, "humanSex");
            return (Criteria) this;
        }

        public Criteria andHumanRemarkIsNull() {
            addCriterion("human_remark is null");
            return (Criteria) this;
        }

        public Criteria andHumanRemarkIsNotNull() {
            addCriterion("human_remark is not null");
            return (Criteria) this;
        }

        public Criteria andHumanRemarkEqualTo(String value) {
            addCriterion("human_remark =", value, "humanRemark");
            return (Criteria) this;
        }

        public Criteria andHumanRemarkNotEqualTo(String value) {
            addCriterion("human_remark <>", value, "humanRemark");
            return (Criteria) this;
        }

        public Criteria andHumanRemarkGreaterThan(String value) {
            addCriterion("human_remark >", value, "humanRemark");
            return (Criteria) this;
        }

        public Criteria andHumanRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("human_remark >=", value, "humanRemark");
            return (Criteria) this;
        }

        public Criteria andHumanRemarkLessThan(String value) {
            addCriterion("human_remark <", value, "humanRemark");
            return (Criteria) this;
        }

        public Criteria andHumanRemarkLessThanOrEqualTo(String value) {
            addCriterion("human_remark <=", value, "humanRemark");
            return (Criteria) this;
        }

        public Criteria andHumanRemarkLike(String value) {
            addCriterion("human_remark like", value, "humanRemark");
            return (Criteria) this;
        }

        public Criteria andHumanRemarkNotLike(String value) {
            addCriterion("human_remark not like", value, "humanRemark");
            return (Criteria) this;
        }

        public Criteria andHumanRemarkIn(List<String> values) {
            addCriterion("human_remark in", values, "humanRemark");
            return (Criteria) this;
        }

        public Criteria andHumanRemarkNotIn(List<String> values) {
            addCriterion("human_remark not in", values, "humanRemark");
            return (Criteria) this;
        }

        public Criteria andHumanRemarkBetween(String value1, String value2) {
            addCriterion("human_remark between", value1, value2, "humanRemark");
            return (Criteria) this;
        }

        public Criteria andHumanRemarkNotBetween(String value1, String value2) {
            addCriterion("human_remark not between", value1, value2, "humanRemark");
            return (Criteria) this;
        }

        public Criteria andHumanPicUrlIsNull() {
            addCriterion("human_pic_url is null");
            return (Criteria) this;
        }

        public Criteria andHumanPicUrlIsNotNull() {
            addCriterion("human_pic_url is not null");
            return (Criteria) this;
        }

        public Criteria andHumanPicUrlEqualTo(String value) {
            addCriterion("human_pic_url =", value, "humanPicUrl");
            return (Criteria) this;
        }

        public Criteria andHumanPicUrlNotEqualTo(String value) {
            addCriterion("human_pic_url <>", value, "humanPicUrl");
            return (Criteria) this;
        }

        public Criteria andHumanPicUrlGreaterThan(String value) {
            addCriterion("human_pic_url >", value, "humanPicUrl");
            return (Criteria) this;
        }

        public Criteria andHumanPicUrlGreaterThanOrEqualTo(String value) {
            addCriterion("human_pic_url >=", value, "humanPicUrl");
            return (Criteria) this;
        }

        public Criteria andHumanPicUrlLessThan(String value) {
            addCriterion("human_pic_url <", value, "humanPicUrl");
            return (Criteria) this;
        }

        public Criteria andHumanPicUrlLessThanOrEqualTo(String value) {
            addCriterion("human_pic_url <=", value, "humanPicUrl");
            return (Criteria) this;
        }

        public Criteria andHumanPicUrlLike(String value) {
            addCriterion("human_pic_url like", value, "humanPicUrl");
            return (Criteria) this;
        }

        public Criteria andHumanPicUrlNotLike(String value) {
            addCriterion("human_pic_url not like", value, "humanPicUrl");
            return (Criteria) this;
        }

        public Criteria andHumanPicUrlIn(List<String> values) {
            addCriterion("human_pic_url in", values, "humanPicUrl");
            return (Criteria) this;
        }

        public Criteria andHumanPicUrlNotIn(List<String> values) {
            addCriterion("human_pic_url not in", values, "humanPicUrl");
            return (Criteria) this;
        }

        public Criteria andHumanPicUrlBetween(String value1, String value2) {
            addCriterion("human_pic_url between", value1, value2, "humanPicUrl");
            return (Criteria) this;
        }

        public Criteria andHumanPicUrlNotBetween(String value1, String value2) {
            addCriterion("human_pic_url not between", value1, value2, "humanPicUrl");
            return (Criteria) this;
        }

        public Criteria andHumanStatusIsNull() {
            addCriterion("human_status is null");
            return (Criteria) this;
        }

        public Criteria andHumanStatusIsNotNull() {
            addCriterion("human_status is not null");
            return (Criteria) this;
        }

        public Criteria andHumanStatusEqualTo(String value) {
            addCriterion("human_status =", value, "humanStatus");
            return (Criteria) this;
        }

        public Criteria andHumanStatusNotEqualTo(String value) {
            addCriterion("human_status <>", value, "humanStatus");
            return (Criteria) this;
        }

        public Criteria andHumanStatusGreaterThan(String value) {
            addCriterion("human_status >", value, "humanStatus");
            return (Criteria) this;
        }

        public Criteria andHumanStatusGreaterThanOrEqualTo(String value) {
            addCriterion("human_status >=", value, "humanStatus");
            return (Criteria) this;
        }

        public Criteria andHumanStatusLessThan(String value) {
            addCriterion("human_status <", value, "humanStatus");
            return (Criteria) this;
        }

        public Criteria andHumanStatusLessThanOrEqualTo(String value) {
            addCriterion("human_status <=", value, "humanStatus");
            return (Criteria) this;
        }

        public Criteria andHumanStatusLike(String value) {
            addCriterion("human_status like", value, "humanStatus");
            return (Criteria) this;
        }

        public Criteria andHumanStatusNotLike(String value) {
            addCriterion("human_status not like", value, "humanStatus");
            return (Criteria) this;
        }

        public Criteria andHumanStatusIn(List<String> values) {
            addCriterion("human_status in", values, "humanStatus");
            return (Criteria) this;
        }

        public Criteria andHumanStatusNotIn(List<String> values) {
            addCriterion("human_status not in", values, "humanStatus");
            return (Criteria) this;
        }

        public Criteria andHumanStatusBetween(String value1, String value2) {
            addCriterion("human_status between", value1, value2, "humanStatus");
            return (Criteria) this;
        }

        public Criteria andHumanStatusNotBetween(String value1, String value2) {
            addCriterion("human_status not between", value1, value2, "humanStatus");
            return (Criteria) this;
        }

        public Criteria andHumanEducationIsNull() {
            addCriterion("human_education is null");
            return (Criteria) this;
        }

        public Criteria andHumanEducationIsNotNull() {
            addCriterion("human_education is not null");
            return (Criteria) this;
        }

        public Criteria andHumanEducationEqualTo(String value) {
            addCriterion("human_education =", value, "humanEducation");
            return (Criteria) this;
        }

        public Criteria andHumanEducationNotEqualTo(String value) {
            addCriterion("human_education <>", value, "humanEducation");
            return (Criteria) this;
        }

        public Criteria andHumanEducationGreaterThan(String value) {
            addCriterion("human_education >", value, "humanEducation");
            return (Criteria) this;
        }

        public Criteria andHumanEducationGreaterThanOrEqualTo(String value) {
            addCriterion("human_education >=", value, "humanEducation");
            return (Criteria) this;
        }

        public Criteria andHumanEducationLessThan(String value) {
            addCriterion("human_education <", value, "humanEducation");
            return (Criteria) this;
        }

        public Criteria andHumanEducationLessThanOrEqualTo(String value) {
            addCriterion("human_education <=", value, "humanEducation");
            return (Criteria) this;
        }

        public Criteria andHumanEducationLike(String value) {
            addCriterion("human_education like", value, "humanEducation");
            return (Criteria) this;
        }

        public Criteria andHumanEducationNotLike(String value) {
            addCriterion("human_education not like", value, "humanEducation");
            return (Criteria) this;
        }

        public Criteria andHumanEducationIn(List<String> values) {
            addCriterion("human_education in", values, "humanEducation");
            return (Criteria) this;
        }

        public Criteria andHumanEducationNotIn(List<String> values) {
            addCriterion("human_education not in", values, "humanEducation");
            return (Criteria) this;
        }

        public Criteria andHumanEducationBetween(String value1, String value2) {
            addCriterion("human_education between", value1, value2, "humanEducation");
            return (Criteria) this;
        }

        public Criteria andHumanEducationNotBetween(String value1, String value2) {
            addCriterion("human_education not between", value1, value2, "humanEducation");
            return (Criteria) this;
        }

        public Criteria andHumanAddressCurrIsNull() {
            addCriterion("human_address_curr is null");
            return (Criteria) this;
        }

        public Criteria andHumanAddressCurrIsNotNull() {
            addCriterion("human_address_curr is not null");
            return (Criteria) this;
        }

        public Criteria andHumanAddressCurrEqualTo(String value) {
            addCriterion("human_address_curr =", value, "humanAddressCurr");
            return (Criteria) this;
        }

        public Criteria andHumanAddressCurrNotEqualTo(String value) {
            addCriterion("human_address_curr <>", value, "humanAddressCurr");
            return (Criteria) this;
        }

        public Criteria andHumanAddressCurrGreaterThan(String value) {
            addCriterion("human_address_curr >", value, "humanAddressCurr");
            return (Criteria) this;
        }

        public Criteria andHumanAddressCurrGreaterThanOrEqualTo(String value) {
            addCriterion("human_address_curr >=", value, "humanAddressCurr");
            return (Criteria) this;
        }

        public Criteria andHumanAddressCurrLessThan(String value) {
            addCriterion("human_address_curr <", value, "humanAddressCurr");
            return (Criteria) this;
        }

        public Criteria andHumanAddressCurrLessThanOrEqualTo(String value) {
            addCriterion("human_address_curr <=", value, "humanAddressCurr");
            return (Criteria) this;
        }

        public Criteria andHumanAddressCurrLike(String value) {
            addCriterion("human_address_curr like", value, "humanAddressCurr");
            return (Criteria) this;
        }

        public Criteria andHumanAddressCurrNotLike(String value) {
            addCriterion("human_address_curr not like", value, "humanAddressCurr");
            return (Criteria) this;
        }

        public Criteria andHumanAddressCurrIn(List<String> values) {
            addCriterion("human_address_curr in", values, "humanAddressCurr");
            return (Criteria) this;
        }

        public Criteria andHumanAddressCurrNotIn(List<String> values) {
            addCriterion("human_address_curr not in", values, "humanAddressCurr");
            return (Criteria) this;
        }

        public Criteria andHumanAddressCurrBetween(String value1, String value2) {
            addCriterion("human_address_curr between", value1, value2, "humanAddressCurr");
            return (Criteria) this;
        }

        public Criteria andHumanAddressCurrNotBetween(String value1, String value2) {
            addCriterion("human_address_curr not between", value1, value2, "humanAddressCurr");
            return (Criteria) this;
        }

        public Criteria andHumanAddressHopeIsNull() {
            addCriterion("human_address_hope is null");
            return (Criteria) this;
        }

        public Criteria andHumanAddressHopeIsNotNull() {
            addCriterion("human_address_hope is not null");
            return (Criteria) this;
        }

        public Criteria andHumanAddressHopeEqualTo(String value) {
            addCriterion("human_address_hope =", value, "humanAddressHope");
            return (Criteria) this;
        }

        public Criteria andHumanAddressHopeNotEqualTo(String value) {
            addCriterion("human_address_hope <>", value, "humanAddressHope");
            return (Criteria) this;
        }

        public Criteria andHumanAddressHopeGreaterThan(String value) {
            addCriterion("human_address_hope >", value, "humanAddressHope");
            return (Criteria) this;
        }

        public Criteria andHumanAddressHopeGreaterThanOrEqualTo(String value) {
            addCriterion("human_address_hope >=", value, "humanAddressHope");
            return (Criteria) this;
        }

        public Criteria andHumanAddressHopeLessThan(String value) {
            addCriterion("human_address_hope <", value, "humanAddressHope");
            return (Criteria) this;
        }

        public Criteria andHumanAddressHopeLessThanOrEqualTo(String value) {
            addCriterion("human_address_hope <=", value, "humanAddressHope");
            return (Criteria) this;
        }

        public Criteria andHumanAddressHopeLike(String value) {
            addCriterion("human_address_hope like", value, "humanAddressHope");
            return (Criteria) this;
        }

        public Criteria andHumanAddressHopeNotLike(String value) {
            addCriterion("human_address_hope not like", value, "humanAddressHope");
            return (Criteria) this;
        }

        public Criteria andHumanAddressHopeIn(List<String> values) {
            addCriterion("human_address_hope in", values, "humanAddressHope");
            return (Criteria) this;
        }

        public Criteria andHumanAddressHopeNotIn(List<String> values) {
            addCriterion("human_address_hope not in", values, "humanAddressHope");
            return (Criteria) this;
        }

        public Criteria andHumanAddressHopeBetween(String value1, String value2) {
            addCriterion("human_address_hope between", value1, value2, "humanAddressHope");
            return (Criteria) this;
        }

        public Criteria andHumanAddressHopeNotBetween(String value1, String value2) {
            addCriterion("human_address_hope not between", value1, value2, "humanAddressHope");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ws_human
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ws_human
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}