package com.sy.modules.entity.ws;

import java.io.Serializable;
import java.util.Date;

public class WsHuman implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ws_human.human_id
     *
     * @mbggenerated
     */
    private Long humanId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ws_human.human_account
     *
     * @mbggenerated
     */
    private String humanAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ws_human.human_password
     *
     * @mbggenerated
     */
    private String humanPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ws_human.human_question
     *
     * @mbggenerated
     */
    private String humanQuestion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ws_human.human_answer
     *
     * @mbggenerated
     */
    private String humanAnswer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ws_human.human_phone
     *
     * @mbggenerated
     */
    private String humanPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ws_human.human_qq
     *
     * @mbggenerated
     */
    private String humanQq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ws_human.human_name
     *
     * @mbggenerated
     */
    private String humanName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ws_human.human_address
     *
     * @mbggenerated
     */
    private String humanAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ws_human.del_statue
     *
     * @mbggenerated
     */
    private Byte delStatue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ws_human.create_name
     *
     * @mbggenerated
     */
    private String createName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ws_human.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ws_human.update_name
     *
     * @mbggenerated
     */
    private String updateName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ws_human.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ws_human.human_sex
     *
     * @mbggenerated
     */
    private String humanSex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ws_human.human_remark
     *
     * @mbggenerated
     */
    private String humanRemark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ws_human.human_pic_url
     *
     * @mbggenerated
     */
    private String humanPicUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ws_human.human_status
     *
     * @mbggenerated
     */
    private String humanStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ws_human.human_education
     *
     * @mbggenerated
     */
    private String humanEducation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ws_human.human_address_curr
     *
     * @mbggenerated
     */
    private String humanAddressCurr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ws_human.human_address_hope
     *
     * @mbggenerated
     */
    private String humanAddressHope;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ws_human
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ws_human.human_id
     *
     * @return the value of ws_human.human_id
     *
     * @mbggenerated
     */
    public Long getHumanId() {
        return humanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ws_human.human_id
     *
     * @param humanId the value for ws_human.human_id
     *
     * @mbggenerated
     */
    public void setHumanId(Long humanId) {
        this.humanId = humanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ws_human.human_account
     *
     * @return the value of ws_human.human_account
     *
     * @mbggenerated
     */
    public String getHumanAccount() {
        return humanAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ws_human.human_account
     *
     * @param humanAccount the value for ws_human.human_account
     *
     * @mbggenerated
     */
    public void setHumanAccount(String humanAccount) {
        this.humanAccount = humanAccount == null ? null : humanAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ws_human.human_password
     *
     * @return the value of ws_human.human_password
     *
     * @mbggenerated
     */
    public String getHumanPassword() {
        return humanPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ws_human.human_password
     *
     * @param humanPassword the value for ws_human.human_password
     *
     * @mbggenerated
     */
    public void setHumanPassword(String humanPassword) {
        this.humanPassword = humanPassword == null ? null : humanPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ws_human.human_question
     *
     * @return the value of ws_human.human_question
     *
     * @mbggenerated
     */
    public String getHumanQuestion() {
        return humanQuestion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ws_human.human_question
     *
     * @param humanQuestion the value for ws_human.human_question
     *
     * @mbggenerated
     */
    public void setHumanQuestion(String humanQuestion) {
        this.humanQuestion = humanQuestion == null ? null : humanQuestion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ws_human.human_answer
     *
     * @return the value of ws_human.human_answer
     *
     * @mbggenerated
     */
    public String getHumanAnswer() {
        return humanAnswer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ws_human.human_answer
     *
     * @param humanAnswer the value for ws_human.human_answer
     *
     * @mbggenerated
     */
    public void setHumanAnswer(String humanAnswer) {
        this.humanAnswer = humanAnswer == null ? null : humanAnswer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ws_human.human_phone
     *
     * @return the value of ws_human.human_phone
     *
     * @mbggenerated
     */
    public String getHumanPhone() {
        return humanPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ws_human.human_phone
     *
     * @param humanPhone the value for ws_human.human_phone
     *
     * @mbggenerated
     */
    public void setHumanPhone(String humanPhone) {
        this.humanPhone = humanPhone == null ? null : humanPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ws_human.human_qq
     *
     * @return the value of ws_human.human_qq
     *
     * @mbggenerated
     */
    public String getHumanQq() {
        return humanQq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ws_human.human_qq
     *
     * @param humanQq the value for ws_human.human_qq
     *
     * @mbggenerated
     */
    public void setHumanQq(String humanQq) {
        this.humanQq = humanQq == null ? null : humanQq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ws_human.human_name
     *
     * @return the value of ws_human.human_name
     *
     * @mbggenerated
     */
    public String getHumanName() {
        return humanName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ws_human.human_name
     *
     * @param humanName the value for ws_human.human_name
     *
     * @mbggenerated
     */
    public void setHumanName(String humanName) {
        this.humanName = humanName == null ? null : humanName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ws_human.human_address
     *
     * @return the value of ws_human.human_address
     *
     * @mbggenerated
     */
    public String getHumanAddress() {
        return humanAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ws_human.human_address
     *
     * @param humanAddress the value for ws_human.human_address
     *
     * @mbggenerated
     */
    public void setHumanAddress(String humanAddress) {
        this.humanAddress = humanAddress == null ? null : humanAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ws_human.del_statue
     *
     * @return the value of ws_human.del_statue
     *
     * @mbggenerated
     */
    public Byte getDelStatue() {
        return delStatue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ws_human.del_statue
     *
     * @param delStatue the value for ws_human.del_statue
     *
     * @mbggenerated
     */
    public void setDelStatue(Byte delStatue) {
        this.delStatue = delStatue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ws_human.create_name
     *
     * @return the value of ws_human.create_name
     *
     * @mbggenerated
     */
    public String getCreateName() {
        return createName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ws_human.create_name
     *
     * @param createName the value for ws_human.create_name
     *
     * @mbggenerated
     */
    public void setCreateName(String createName) {
        this.createName = createName == null ? null : createName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ws_human.create_time
     *
     * @return the value of ws_human.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ws_human.create_time
     *
     * @param createTime the value for ws_human.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ws_human.update_name
     *
     * @return the value of ws_human.update_name
     *
     * @mbggenerated
     */
    public String getUpdateName() {
        return updateName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ws_human.update_name
     *
     * @param updateName the value for ws_human.update_name
     *
     * @mbggenerated
     */
    public void setUpdateName(String updateName) {
        this.updateName = updateName == null ? null : updateName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ws_human.update_time
     *
     * @return the value of ws_human.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ws_human.update_time
     *
     * @param updateTime the value for ws_human.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ws_human.human_sex
     *
     * @return the value of ws_human.human_sex
     *
     * @mbggenerated
     */
    public String getHumanSex() {
        return humanSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ws_human.human_sex
     *
     * @param humanSex the value for ws_human.human_sex
     *
     * @mbggenerated
     */
    public void setHumanSex(String humanSex) {
        this.humanSex = humanSex == null ? null : humanSex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ws_human.human_remark
     *
     * @return the value of ws_human.human_remark
     *
     * @mbggenerated
     */
    public String getHumanRemark() {
        return humanRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ws_human.human_remark
     *
     * @param humanRemark the value for ws_human.human_remark
     *
     * @mbggenerated
     */
    public void setHumanRemark(String humanRemark) {
        this.humanRemark = humanRemark == null ? null : humanRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ws_human.human_pic_url
     *
     * @return the value of ws_human.human_pic_url
     *
     * @mbggenerated
     */
    public String getHumanPicUrl() {
        return humanPicUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ws_human.human_pic_url
     *
     * @param humanPicUrl the value for ws_human.human_pic_url
     *
     * @mbggenerated
     */
    public void setHumanPicUrl(String humanPicUrl) {
        this.humanPicUrl = humanPicUrl == null ? null : humanPicUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ws_human.human_status
     *
     * @return the value of ws_human.human_status
     *
     * @mbggenerated
     */
    public String getHumanStatus() {
        return humanStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ws_human.human_status
     *
     * @param humanStatus the value for ws_human.human_status
     *
     * @mbggenerated
     */
    public void setHumanStatus(String humanStatus) {
        this.humanStatus = humanStatus == null ? null : humanStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ws_human.human_education
     *
     * @return the value of ws_human.human_education
     *
     * @mbggenerated
     */
    public String getHumanEducation() {
        return humanEducation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ws_human.human_education
     *
     * @param humanEducation the value for ws_human.human_education
     *
     * @mbggenerated
     */
    public void setHumanEducation(String humanEducation) {
        this.humanEducation = humanEducation == null ? null : humanEducation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ws_human.human_address_curr
     *
     * @return the value of ws_human.human_address_curr
     *
     * @mbggenerated
     */
    public String getHumanAddressCurr() {
        return humanAddressCurr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ws_human.human_address_curr
     *
     * @param humanAddressCurr the value for ws_human.human_address_curr
     *
     * @mbggenerated
     */
    public void setHumanAddressCurr(String humanAddressCurr) {
        this.humanAddressCurr = humanAddressCurr == null ? null : humanAddressCurr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ws_human.human_address_hope
     *
     * @return the value of ws_human.human_address_hope
     *
     * @mbggenerated
     */
    public String getHumanAddressHope() {
        return humanAddressHope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ws_human.human_address_hope
     *
     * @param humanAddressHope the value for ws_human.human_address_hope
     *
     * @mbggenerated
     */
    public void setHumanAddressHope(String humanAddressHope) {
        this.humanAddressHope = humanAddressHope == null ? null : humanAddressHope.trim();
    }
}