package com.sy.modules.entity.ws;

import java.io.Serializable;
import java.util.Date;

public class WsOrder implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ws_order.o_id
     *
     * @mbggenerated
     */
    private Integer oId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ws_order.o_number
     *
     * @mbggenerated
     */
    private String oNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ws_order.o_human_id
     *
     * @mbggenerated
     */
    private Integer oHumanId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ws_order.o_human_name
     *
     * @mbggenerated
     */
    private String oHumanName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ws_order.o_company_id
     *
     * @mbggenerated
     */
    private Integer oCompanyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ws_order.o_company
     *
     * @mbggenerated
     */
    private String oCompany;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ws_order.o_job
     *
     * @mbggenerated
     */
    private String oJob;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ws_order.o_job_salary
     *
     * @mbggenerated
     */
    private String oJobSalary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ws_order.o_job_salary_day
     *
     * @mbggenerated
     */
    private String oJobSalaryDay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ws_order.o_status
     *
     * @mbggenerated
     */
    private String oStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ws_order.o_username
     *
     * @mbggenerated
     */
    private String oUsername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ws_order.o_remark
     *
     * @mbggenerated
     */
    private String oRemark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ws_order.del_status
     *
     * @mbggenerated
     */
    private String delStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ws_order.create_name
     *
     * @mbggenerated
     */
    private String createName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ws_order.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ws_order.update_name
     *
     * @mbggenerated
     */
    private String updateName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ws_order.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ws_order
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ws_order.o_id
     *
     * @return the value of ws_order.o_id
     *
     * @mbggenerated
     */
    public Integer getoId() {
        return oId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ws_order.o_id
     *
     * @param oId the value for ws_order.o_id
     *
     * @mbggenerated
     */
    public void setoId(Integer oId) {
        this.oId = oId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ws_order.o_number
     *
     * @return the value of ws_order.o_number
     *
     * @mbggenerated
     */
    public String getoNumber() {
        return oNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ws_order.o_number
     *
     * @param oNumber the value for ws_order.o_number
     *
     * @mbggenerated
     */
    public void setoNumber(String oNumber) {
        this.oNumber = oNumber == null ? null : oNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ws_order.o_human_id
     *
     * @return the value of ws_order.o_human_id
     *
     * @mbggenerated
     */
    public Integer getoHumanId() {
        return oHumanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ws_order.o_human_id
     *
     * @param oHumanId the value for ws_order.o_human_id
     *
     * @mbggenerated
     */
    public void setoHumanId(Integer oHumanId) {
        this.oHumanId = oHumanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ws_order.o_human_name
     *
     * @return the value of ws_order.o_human_name
     *
     * @mbggenerated
     */
    public String getoHumanName() {
        return oHumanName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ws_order.o_human_name
     *
     * @param oHumanName the value for ws_order.o_human_name
     *
     * @mbggenerated
     */
    public void setoHumanName(String oHumanName) {
        this.oHumanName = oHumanName == null ? null : oHumanName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ws_order.o_company_id
     *
     * @return the value of ws_order.o_company_id
     *
     * @mbggenerated
     */
    public Integer getoCompanyId() {
        return oCompanyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ws_order.o_company_id
     *
     * @param oCompanyId the value for ws_order.o_company_id
     *
     * @mbggenerated
     */
    public void setoCompanyId(Integer oCompanyId) {
        this.oCompanyId = oCompanyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ws_order.o_company
     *
     * @return the value of ws_order.o_company
     *
     * @mbggenerated
     */
    public String getoCompany() {
        return oCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ws_order.o_company
     *
     * @param oCompany the value for ws_order.o_company
     *
     * @mbggenerated
     */
    public void setoCompany(String oCompany) {
        this.oCompany = oCompany == null ? null : oCompany.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ws_order.o_job
     *
     * @return the value of ws_order.o_job
     *
     * @mbggenerated
     */
    public String getoJob() {
        return oJob;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ws_order.o_job
     *
     * @param oJob the value for ws_order.o_job
     *
     * @mbggenerated
     */
    public void setoJob(String oJob) {
        this.oJob = oJob == null ? null : oJob.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ws_order.o_job_salary
     *
     * @return the value of ws_order.o_job_salary
     *
     * @mbggenerated
     */
    public String getoJobSalary() {
        return oJobSalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ws_order.o_job_salary
     *
     * @param oJobSalary the value for ws_order.o_job_salary
     *
     * @mbggenerated
     */
    public void setoJobSalary(String oJobSalary) {
        this.oJobSalary = oJobSalary == null ? null : oJobSalary.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ws_order.o_job_salary_day
     *
     * @return the value of ws_order.o_job_salary_day
     *
     * @mbggenerated
     */
    public String getoJobSalaryDay() {
        return oJobSalaryDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ws_order.o_job_salary_day
     *
     * @param oJobSalaryDay the value for ws_order.o_job_salary_day
     *
     * @mbggenerated
     */
    public void setoJobSalaryDay(String oJobSalaryDay) {
        this.oJobSalaryDay = oJobSalaryDay == null ? null : oJobSalaryDay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ws_order.o_status
     *
     * @return the value of ws_order.o_status
     *
     * @mbggenerated
     */
    public String getoStatus() {
        return oStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ws_order.o_status
     *
     * @param oStatus the value for ws_order.o_status
     *
     * @mbggenerated
     */
    public void setoStatus(String oStatus) {
        this.oStatus = oStatus == null ? null : oStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ws_order.o_username
     *
     * @return the value of ws_order.o_username
     *
     * @mbggenerated
     */
    public String getoUsername() {
        return oUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ws_order.o_username
     *
     * @param oUsername the value for ws_order.o_username
     *
     * @mbggenerated
     */
    public void setoUsername(String oUsername) {
        this.oUsername = oUsername == null ? null : oUsername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ws_order.o_remark
     *
     * @return the value of ws_order.o_remark
     *
     * @mbggenerated
     */
    public String getoRemark() {
        return oRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ws_order.o_remark
     *
     * @param oRemark the value for ws_order.o_remark
     *
     * @mbggenerated
     */
    public void setoRemark(String oRemark) {
        this.oRemark = oRemark == null ? null : oRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ws_order.del_status
     *
     * @return the value of ws_order.del_status
     *
     * @mbggenerated
     */
    public String getDelStatus() {
        return delStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ws_order.del_status
     *
     * @param delStatus the value for ws_order.del_status
     *
     * @mbggenerated
     */
    public void setDelStatus(String delStatus) {
        this.delStatus = delStatus == null ? null : delStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ws_order.create_name
     *
     * @return the value of ws_order.create_name
     *
     * @mbggenerated
     */
    public String getCreateName() {
        return createName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ws_order.create_name
     *
     * @param createName the value for ws_order.create_name
     *
     * @mbggenerated
     */
    public void setCreateName(String createName) {
        this.createName = createName == null ? null : createName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ws_order.create_time
     *
     * @return the value of ws_order.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ws_order.create_time
     *
     * @param createTime the value for ws_order.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ws_order.update_name
     *
     * @return the value of ws_order.update_name
     *
     * @mbggenerated
     */
    public String getUpdateName() {
        return updateName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ws_order.update_name
     *
     * @param updateName the value for ws_order.update_name
     *
     * @mbggenerated
     */
    public void setUpdateName(String updateName) {
        this.updateName = updateName == null ? null : updateName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ws_order.update_time
     *
     * @return the value of ws_order.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ws_order.update_time
     *
     * @param updateTime the value for ws_order.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}