package com.sy.modules.entity.ws;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class WsOrderExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ws_order
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ws_order
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ws_order
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ws_order
     *
     * @mbggenerated
     */
    public WsOrderExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ws_order
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ws_order
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ws_order
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ws_order
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ws_order
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ws_order
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ws_order
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ws_order
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ws_order
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ws_order
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ws_order
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andOIdIsNull() {
            addCriterion("o_id is null");
            return (Criteria) this;
        }

        public Criteria andOIdIsNotNull() {
            addCriterion("o_id is not null");
            return (Criteria) this;
        }

        public Criteria andOIdEqualTo(Integer value) {
            addCriterion("o_id =", value, "oId");
            return (Criteria) this;
        }

        public Criteria andOIdNotEqualTo(Integer value) {
            addCriterion("o_id <>", value, "oId");
            return (Criteria) this;
        }

        public Criteria andOIdGreaterThan(Integer value) {
            addCriterion("o_id >", value, "oId");
            return (Criteria) this;
        }

        public Criteria andOIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("o_id >=", value, "oId");
            return (Criteria) this;
        }

        public Criteria andOIdLessThan(Integer value) {
            addCriterion("o_id <", value, "oId");
            return (Criteria) this;
        }

        public Criteria andOIdLessThanOrEqualTo(Integer value) {
            addCriterion("o_id <=", value, "oId");
            return (Criteria) this;
        }

        public Criteria andOIdIn(List<Integer> values) {
            addCriterion("o_id in", values, "oId");
            return (Criteria) this;
        }

        public Criteria andOIdNotIn(List<Integer> values) {
            addCriterion("o_id not in", values, "oId");
            return (Criteria) this;
        }

        public Criteria andOIdBetween(Integer value1, Integer value2) {
            addCriterion("o_id between", value1, value2, "oId");
            return (Criteria) this;
        }

        public Criteria andOIdNotBetween(Integer value1, Integer value2) {
            addCriterion("o_id not between", value1, value2, "oId");
            return (Criteria) this;
        }

        public Criteria andONumberIsNull() {
            addCriterion("o_number is null");
            return (Criteria) this;
        }

        public Criteria andONumberIsNotNull() {
            addCriterion("o_number is not null");
            return (Criteria) this;
        }

        public Criteria andONumberEqualTo(String value) {
            addCriterion("o_number =", value, "oNumber");
            return (Criteria) this;
        }

        public Criteria andONumberNotEqualTo(String value) {
            addCriterion("o_number <>", value, "oNumber");
            return (Criteria) this;
        }

        public Criteria andONumberGreaterThan(String value) {
            addCriterion("o_number >", value, "oNumber");
            return (Criteria) this;
        }

        public Criteria andONumberGreaterThanOrEqualTo(String value) {
            addCriterion("o_number >=", value, "oNumber");
            return (Criteria) this;
        }

        public Criteria andONumberLessThan(String value) {
            addCriterion("o_number <", value, "oNumber");
            return (Criteria) this;
        }

        public Criteria andONumberLessThanOrEqualTo(String value) {
            addCriterion("o_number <=", value, "oNumber");
            return (Criteria) this;
        }

        public Criteria andONumberLike(String value) {
            addCriterion("o_number like", value, "oNumber");
            return (Criteria) this;
        }

        public Criteria andONumberNotLike(String value) {
            addCriterion("o_number not like", value, "oNumber");
            return (Criteria) this;
        }

        public Criteria andONumberIn(List<String> values) {
            addCriterion("o_number in", values, "oNumber");
            return (Criteria) this;
        }

        public Criteria andONumberNotIn(List<String> values) {
            addCriterion("o_number not in", values, "oNumber");
            return (Criteria) this;
        }

        public Criteria andONumberBetween(String value1, String value2) {
            addCriterion("o_number between", value1, value2, "oNumber");
            return (Criteria) this;
        }

        public Criteria andONumberNotBetween(String value1, String value2) {
            addCriterion("o_number not between", value1, value2, "oNumber");
            return (Criteria) this;
        }

        public Criteria andOHumanIdIsNull() {
            addCriterion("o_human_id is null");
            return (Criteria) this;
        }

        public Criteria andOHumanIdIsNotNull() {
            addCriterion("o_human_id is not null");
            return (Criteria) this;
        }

        public Criteria andOHumanIdEqualTo(Integer value) {
            addCriterion("o_human_id =", value, "oHumanId");
            return (Criteria) this;
        }

        public Criteria andOHumanIdNotEqualTo(Integer value) {
            addCriterion("o_human_id <>", value, "oHumanId");
            return (Criteria) this;
        }

        public Criteria andOHumanIdGreaterThan(Integer value) {
            addCriterion("o_human_id >", value, "oHumanId");
            return (Criteria) this;
        }

        public Criteria andOHumanIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("o_human_id >=", value, "oHumanId");
            return (Criteria) this;
        }

        public Criteria andOHumanIdLessThan(Integer value) {
            addCriterion("o_human_id <", value, "oHumanId");
            return (Criteria) this;
        }

        public Criteria andOHumanIdLessThanOrEqualTo(Integer value) {
            addCriterion("o_human_id <=", value, "oHumanId");
            return (Criteria) this;
        }

        public Criteria andOHumanIdIn(List<Integer> values) {
            addCriterion("o_human_id in", values, "oHumanId");
            return (Criteria) this;
        }

        public Criteria andOHumanIdNotIn(List<Integer> values) {
            addCriterion("o_human_id not in", values, "oHumanId");
            return (Criteria) this;
        }

        public Criteria andOHumanIdBetween(Integer value1, Integer value2) {
            addCriterion("o_human_id between", value1, value2, "oHumanId");
            return (Criteria) this;
        }

        public Criteria andOHumanIdNotBetween(Integer value1, Integer value2) {
            addCriterion("o_human_id not between", value1, value2, "oHumanId");
            return (Criteria) this;
        }

        public Criteria andOHumanNameIsNull() {
            addCriterion("o_human_name is null");
            return (Criteria) this;
        }

        public Criteria andOHumanNameIsNotNull() {
            addCriterion("o_human_name is not null");
            return (Criteria) this;
        }

        public Criteria andOHumanNameEqualTo(String value) {
            addCriterion("o_human_name =", value, "oHumanName");
            return (Criteria) this;
        }

        public Criteria andOHumanNameNotEqualTo(String value) {
            addCriterion("o_human_name <>", value, "oHumanName");
            return (Criteria) this;
        }

        public Criteria andOHumanNameGreaterThan(String value) {
            addCriterion("o_human_name >", value, "oHumanName");
            return (Criteria) this;
        }

        public Criteria andOHumanNameGreaterThanOrEqualTo(String value) {
            addCriterion("o_human_name >=", value, "oHumanName");
            return (Criteria) this;
        }

        public Criteria andOHumanNameLessThan(String value) {
            addCriterion("o_human_name <", value, "oHumanName");
            return (Criteria) this;
        }

        public Criteria andOHumanNameLessThanOrEqualTo(String value) {
            addCriterion("o_human_name <=", value, "oHumanName");
            return (Criteria) this;
        }

        public Criteria andOHumanNameLike(String value) {
            addCriterion("o_human_name like", value, "oHumanName");
            return (Criteria) this;
        }

        public Criteria andOHumanNameNotLike(String value) {
            addCriterion("o_human_name not like", value, "oHumanName");
            return (Criteria) this;
        }

        public Criteria andOHumanNameIn(List<String> values) {
            addCriterion("o_human_name in", values, "oHumanName");
            return (Criteria) this;
        }

        public Criteria andOHumanNameNotIn(List<String> values) {
            addCriterion("o_human_name not in", values, "oHumanName");
            return (Criteria) this;
        }

        public Criteria andOHumanNameBetween(String value1, String value2) {
            addCriterion("o_human_name between", value1, value2, "oHumanName");
            return (Criteria) this;
        }

        public Criteria andOHumanNameNotBetween(String value1, String value2) {
            addCriterion("o_human_name not between", value1, value2, "oHumanName");
            return (Criteria) this;
        }

        public Criteria andOCompanyIsNull() {
            addCriterion("o_company is null");
            return (Criteria) this;
        }

        public Criteria andOCompanyIsNotNull() {
            addCriterion("o_company is not null");
            return (Criteria) this;
        }

        public Criteria andOCompanyEqualTo(String value) {
            addCriterion("o_company =", value, "oCompany");
            return (Criteria) this;
        }

        public Criteria andOCompanyNotEqualTo(String value) {
            addCriterion("o_company <>", value, "oCompany");
            return (Criteria) this;
        }

        public Criteria andOCompanyGreaterThan(String value) {
            addCriterion("o_company >", value, "oCompany");
            return (Criteria) this;
        }

        public Criteria andOCompanyGreaterThanOrEqualTo(String value) {
            addCriterion("o_company >=", value, "oCompany");
            return (Criteria) this;
        }

        public Criteria andOCompanyLessThan(String value) {
            addCriterion("o_company <", value, "oCompany");
            return (Criteria) this;
        }

        public Criteria andOCompanyLessThanOrEqualTo(String value) {
            addCriterion("o_company <=", value, "oCompany");
            return (Criteria) this;
        }

        public Criteria andOCompanyLike(String value) {
            addCriterion("o_company like", value, "oCompany");
            return (Criteria) this;
        }

        public Criteria andOCompanyNotLike(String value) {
            addCriterion("o_company not like", value, "oCompany");
            return (Criteria) this;
        }

        public Criteria andOCompanyIn(List<String> values) {
            addCriterion("o_company in", values, "oCompany");
            return (Criteria) this;
        }

        public Criteria andOCompanyNotIn(List<String> values) {
            addCriterion("o_company not in", values, "oCompany");
            return (Criteria) this;
        }

        public Criteria andOCompanyBetween(String value1, String value2) {
            addCriterion("o_company between", value1, value2, "oCompany");
            return (Criteria) this;
        }

        public Criteria andOCompanyNotBetween(String value1, String value2) {
            addCriterion("o_company not between", value1, value2, "oCompany");
            return (Criteria) this;
        }

        public Criteria andOJobIsNull() {
            addCriterion("o_job is null");
            return (Criteria) this;
        }

        public Criteria andOJobIsNotNull() {
            addCriterion("o_job is not null");
            return (Criteria) this;
        }

        public Criteria andOJobEqualTo(String value) {
            addCriterion("o_job =", value, "oJob");
            return (Criteria) this;
        }

        public Criteria andOJobNotEqualTo(String value) {
            addCriterion("o_job <>", value, "oJob");
            return (Criteria) this;
        }

        public Criteria andOJobGreaterThan(String value) {
            addCriterion("o_job >", value, "oJob");
            return (Criteria) this;
        }

        public Criteria andOJobGreaterThanOrEqualTo(String value) {
            addCriterion("o_job >=", value, "oJob");
            return (Criteria) this;
        }

        public Criteria andOJobLessThan(String value) {
            addCriterion("o_job <", value, "oJob");
            return (Criteria) this;
        }

        public Criteria andOJobLessThanOrEqualTo(String value) {
            addCriterion("o_job <=", value, "oJob");
            return (Criteria) this;
        }

        public Criteria andOJobLike(String value) {
            addCriterion("o_job like", value, "oJob");
            return (Criteria) this;
        }

        public Criteria andOJobNotLike(String value) {
            addCriterion("o_job not like", value, "oJob");
            return (Criteria) this;
        }

        public Criteria andOJobIn(List<String> values) {
            addCriterion("o_job in", values, "oJob");
            return (Criteria) this;
        }

        public Criteria andOJobNotIn(List<String> values) {
            addCriterion("o_job not in", values, "oJob");
            return (Criteria) this;
        }

        public Criteria andOJobBetween(String value1, String value2) {
            addCriterion("o_job between", value1, value2, "oJob");
            return (Criteria) this;
        }

        public Criteria andOJobNotBetween(String value1, String value2) {
            addCriterion("o_job not between", value1, value2, "oJob");
            return (Criteria) this;
        }

        public Criteria andOJobSalaryIsNull() {
            addCriterion("o_job_salary is null");
            return (Criteria) this;
        }

        public Criteria andOJobSalaryIsNotNull() {
            addCriterion("o_job_salary is not null");
            return (Criteria) this;
        }

        public Criteria andOJobSalaryEqualTo(String value) {
            addCriterion("o_job_salary =", value, "oJobSalary");
            return (Criteria) this;
        }

        public Criteria andOJobSalaryNotEqualTo(String value) {
            addCriterion("o_job_salary <>", value, "oJobSalary");
            return (Criteria) this;
        }

        public Criteria andOJobSalaryGreaterThan(String value) {
            addCriterion("o_job_salary >", value, "oJobSalary");
            return (Criteria) this;
        }

        public Criteria andOJobSalaryGreaterThanOrEqualTo(String value) {
            addCriterion("o_job_salary >=", value, "oJobSalary");
            return (Criteria) this;
        }

        public Criteria andOJobSalaryLessThan(String value) {
            addCriterion("o_job_salary <", value, "oJobSalary");
            return (Criteria) this;
        }

        public Criteria andOJobSalaryLessThanOrEqualTo(String value) {
            addCriterion("o_job_salary <=", value, "oJobSalary");
            return (Criteria) this;
        }

        public Criteria andOJobSalaryLike(String value) {
            addCriterion("o_job_salary like", value, "oJobSalary");
            return (Criteria) this;
        }

        public Criteria andOJobSalaryNotLike(String value) {
            addCriterion("o_job_salary not like", value, "oJobSalary");
            return (Criteria) this;
        }

        public Criteria andOJobSalaryIn(List<String> values) {
            addCriterion("o_job_salary in", values, "oJobSalary");
            return (Criteria) this;
        }

        public Criteria andOJobSalaryNotIn(List<String> values) {
            addCriterion("o_job_salary not in", values, "oJobSalary");
            return (Criteria) this;
        }

        public Criteria andOJobSalaryBetween(String value1, String value2) {
            addCriterion("o_job_salary between", value1, value2, "oJobSalary");
            return (Criteria) this;
        }

        public Criteria andOJobSalaryNotBetween(String value1, String value2) {
            addCriterion("o_job_salary not between", value1, value2, "oJobSalary");
            return (Criteria) this;
        }

        public Criteria andOJobSalaryDayIsNull() {
            addCriterion("o_job_salary_day is null");
            return (Criteria) this;
        }

        public Criteria andOJobSalaryDayIsNotNull() {
            addCriterion("o_job_salary_day is not null");
            return (Criteria) this;
        }

        public Criteria andOJobSalaryDayEqualTo(String value) {
            addCriterion("o_job_salary_day =", value, "oJobSalaryDay");
            return (Criteria) this;
        }

        public Criteria andOJobSalaryDayNotEqualTo(String value) {
            addCriterion("o_job_salary_day <>", value, "oJobSalaryDay");
            return (Criteria) this;
        }

        public Criteria andOJobSalaryDayGreaterThan(String value) {
            addCriterion("o_job_salary_day >", value, "oJobSalaryDay");
            return (Criteria) this;
        }

        public Criteria andOJobSalaryDayGreaterThanOrEqualTo(String value) {
            addCriterion("o_job_salary_day >=", value, "oJobSalaryDay");
            return (Criteria) this;
        }

        public Criteria andOJobSalaryDayLessThan(String value) {
            addCriterion("o_job_salary_day <", value, "oJobSalaryDay");
            return (Criteria) this;
        }

        public Criteria andOJobSalaryDayLessThanOrEqualTo(String value) {
            addCriterion("o_job_salary_day <=", value, "oJobSalaryDay");
            return (Criteria) this;
        }

        public Criteria andOJobSalaryDayLike(String value) {
            addCriterion("o_job_salary_day like", value, "oJobSalaryDay");
            return (Criteria) this;
        }

        public Criteria andOJobSalaryDayNotLike(String value) {
            addCriterion("o_job_salary_day not like", value, "oJobSalaryDay");
            return (Criteria) this;
        }

        public Criteria andOJobSalaryDayIn(List<String> values) {
            addCriterion("o_job_salary_day in", values, "oJobSalaryDay");
            return (Criteria) this;
        }

        public Criteria andOJobSalaryDayNotIn(List<String> values) {
            addCriterion("o_job_salary_day not in", values, "oJobSalaryDay");
            return (Criteria) this;
        }

        public Criteria andOJobSalaryDayBetween(String value1, String value2) {
            addCriterion("o_job_salary_day between", value1, value2, "oJobSalaryDay");
            return (Criteria) this;
        }

        public Criteria andOJobSalaryDayNotBetween(String value1, String value2) {
            addCriterion("o_job_salary_day not between", value1, value2, "oJobSalaryDay");
            return (Criteria) this;
        }

        public Criteria andOStatusIsNull() {
            addCriterion("o_status is null");
            return (Criteria) this;
        }

        public Criteria andOStatusIsNotNull() {
            addCriterion("o_status is not null");
            return (Criteria) this;
        }

        public Criteria andOStatusEqualTo(String value) {
            addCriterion("o_status =", value, "oStatus");
            return (Criteria) this;
        }

        public Criteria andOStatusNotEqualTo(String value) {
            addCriterion("o_status <>", value, "oStatus");
            return (Criteria) this;
        }

        public Criteria andOStatusGreaterThan(String value) {
            addCriterion("o_status >", value, "oStatus");
            return (Criteria) this;
        }

        public Criteria andOStatusGreaterThanOrEqualTo(String value) {
            addCriterion("o_status >=", value, "oStatus");
            return (Criteria) this;
        }

        public Criteria andOStatusLessThan(String value) {
            addCriterion("o_status <", value, "oStatus");
            return (Criteria) this;
        }

        public Criteria andOStatusLessThanOrEqualTo(String value) {
            addCriterion("o_status <=", value, "oStatus");
            return (Criteria) this;
        }

        public Criteria andOStatusLike(String value) {
            addCriterion("o_status like", value, "oStatus");
            return (Criteria) this;
        }

        public Criteria andOStatusNotLike(String value) {
            addCriterion("o_status not like", value, "oStatus");
            return (Criteria) this;
        }

        public Criteria andOStatusIn(List<String> values) {
            addCriterion("o_status in", values, "oStatus");
            return (Criteria) this;
        }

        public Criteria andOStatusNotIn(List<String> values) {
            addCriterion("o_status not in", values, "oStatus");
            return (Criteria) this;
        }

        public Criteria andOStatusBetween(String value1, String value2) {
            addCriterion("o_status between", value1, value2, "oStatus");
            return (Criteria) this;
        }

        public Criteria andOStatusNotBetween(String value1, String value2) {
            addCriterion("o_status not between", value1, value2, "oStatus");
            return (Criteria) this;
        }

        public Criteria andOUsernameIsNull() {
            addCriterion("o_username is null");
            return (Criteria) this;
        }

        public Criteria andOUsernameIsNotNull() {
            addCriterion("o_username is not null");
            return (Criteria) this;
        }

        public Criteria andOUsernameEqualTo(String value) {
            addCriterion("o_username =", value, "oUsername");
            return (Criteria) this;
        }

        public Criteria andOUsernameNotEqualTo(String value) {
            addCriterion("o_username <>", value, "oUsername");
            return (Criteria) this;
        }

        public Criteria andOUsernameGreaterThan(String value) {
            addCriterion("o_username >", value, "oUsername");
            return (Criteria) this;
        }

        public Criteria andOUsernameGreaterThanOrEqualTo(String value) {
            addCriterion("o_username >=", value, "oUsername");
            return (Criteria) this;
        }

        public Criteria andOUsernameLessThan(String value) {
            addCriterion("o_username <", value, "oUsername");
            return (Criteria) this;
        }

        public Criteria andOUsernameLessThanOrEqualTo(String value) {
            addCriterion("o_username <=", value, "oUsername");
            return (Criteria) this;
        }

        public Criteria andOUsernameLike(String value) {
            addCriterion("o_username like", value, "oUsername");
            return (Criteria) this;
        }

        public Criteria andOUsernameNotLike(String value) {
            addCriterion("o_username not like", value, "oUsername");
            return (Criteria) this;
        }

        public Criteria andOUsernameIn(List<String> values) {
            addCriterion("o_username in", values, "oUsername");
            return (Criteria) this;
        }

        public Criteria andOUsernameNotIn(List<String> values) {
            addCriterion("o_username not in", values, "oUsername");
            return (Criteria) this;
        }

        public Criteria andOUsernameBetween(String value1, String value2) {
            addCriterion("o_username between", value1, value2, "oUsername");
            return (Criteria) this;
        }

        public Criteria andOUsernameNotBetween(String value1, String value2) {
            addCriterion("o_username not between", value1, value2, "oUsername");
            return (Criteria) this;
        }

        public Criteria andORemarkIsNull() {
            addCriterion("o_remark is null");
            return (Criteria) this;
        }

        public Criteria andORemarkIsNotNull() {
            addCriterion("o_remark is not null");
            return (Criteria) this;
        }

        public Criteria andORemarkEqualTo(String value) {
            addCriterion("o_remark =", value, "oRemark");
            return (Criteria) this;
        }

        public Criteria andORemarkNotEqualTo(String value) {
            addCriterion("o_remark <>", value, "oRemark");
            return (Criteria) this;
        }

        public Criteria andORemarkGreaterThan(String value) {
            addCriterion("o_remark >", value, "oRemark");
            return (Criteria) this;
        }

        public Criteria andORemarkGreaterThanOrEqualTo(String value) {
            addCriterion("o_remark >=", value, "oRemark");
            return (Criteria) this;
        }

        public Criteria andORemarkLessThan(String value) {
            addCriterion("o_remark <", value, "oRemark");
            return (Criteria) this;
        }

        public Criteria andORemarkLessThanOrEqualTo(String value) {
            addCriterion("o_remark <=", value, "oRemark");
            return (Criteria) this;
        }

        public Criteria andORemarkLike(String value) {
            addCriterion("o_remark like", value, "oRemark");
            return (Criteria) this;
        }

        public Criteria andORemarkNotLike(String value) {
            addCriterion("o_remark not like", value, "oRemark");
            return (Criteria) this;
        }

        public Criteria andORemarkIn(List<String> values) {
            addCriterion("o_remark in", values, "oRemark");
            return (Criteria) this;
        }

        public Criteria andORemarkNotIn(List<String> values) {
            addCriterion("o_remark not in", values, "oRemark");
            return (Criteria) this;
        }

        public Criteria andORemarkBetween(String value1, String value2) {
            addCriterion("o_remark between", value1, value2, "oRemark");
            return (Criteria) this;
        }

        public Criteria andORemarkNotBetween(String value1, String value2) {
            addCriterion("o_remark not between", value1, value2, "oRemark");
            return (Criteria) this;
        }

        public Criteria andDelStatusIsNull() {
            addCriterion("del_status is null");
            return (Criteria) this;
        }

        public Criteria andDelStatusIsNotNull() {
            addCriterion("del_status is not null");
            return (Criteria) this;
        }

        public Criteria andDelStatusEqualTo(String value) {
            addCriterion("del_status =", value, "delStatus");
            return (Criteria) this;
        }

        public Criteria andDelStatusNotEqualTo(String value) {
            addCriterion("del_status <>", value, "delStatus");
            return (Criteria) this;
        }

        public Criteria andDelStatusGreaterThan(String value) {
            addCriterion("del_status >", value, "delStatus");
            return (Criteria) this;
        }

        public Criteria andDelStatusGreaterThanOrEqualTo(String value) {
            addCriterion("del_status >=", value, "delStatus");
            return (Criteria) this;
        }

        public Criteria andDelStatusLessThan(String value) {
            addCriterion("del_status <", value, "delStatus");
            return (Criteria) this;
        }

        public Criteria andDelStatusLessThanOrEqualTo(String value) {
            addCriterion("del_status <=", value, "delStatus");
            return (Criteria) this;
        }

        public Criteria andDelStatusLike(String value) {
            addCriterion("del_status like", value, "delStatus");
            return (Criteria) this;
        }

        public Criteria andDelStatusNotLike(String value) {
            addCriterion("del_status not like", value, "delStatus");
            return (Criteria) this;
        }

        public Criteria andDelStatusIn(List<String> values) {
            addCriterion("del_status in", values, "delStatus");
            return (Criteria) this;
        }

        public Criteria andDelStatusNotIn(List<String> values) {
            addCriterion("del_status not in", values, "delStatus");
            return (Criteria) this;
        }

        public Criteria andDelStatusBetween(String value1, String value2) {
            addCriterion("del_status between", value1, value2, "delStatus");
            return (Criteria) this;
        }

        public Criteria andDelStatusNotBetween(String value1, String value2) {
            addCriterion("del_status not between", value1, value2, "delStatus");
            return (Criteria) this;
        }

        public Criteria andCreateNameIsNull() {
            addCriterion("create_name is null");
            return (Criteria) this;
        }

        public Criteria andCreateNameIsNotNull() {
            addCriterion("create_name is not null");
            return (Criteria) this;
        }

        public Criteria andCreateNameEqualTo(String value) {
            addCriterion("create_name =", value, "createName");
            return (Criteria) this;
        }

        public Criteria andCreateNameNotEqualTo(String value) {
            addCriterion("create_name <>", value, "createName");
            return (Criteria) this;
        }

        public Criteria andCreateNameGreaterThan(String value) {
            addCriterion("create_name >", value, "createName");
            return (Criteria) this;
        }

        public Criteria andCreateNameGreaterThanOrEqualTo(String value) {
            addCriterion("create_name >=", value, "createName");
            return (Criteria) this;
        }

        public Criteria andCreateNameLessThan(String value) {
            addCriterion("create_name <", value, "createName");
            return (Criteria) this;
        }

        public Criteria andCreateNameLessThanOrEqualTo(String value) {
            addCriterion("create_name <=", value, "createName");
            return (Criteria) this;
        }

        public Criteria andCreateNameLike(String value) {
            addCriterion("create_name like", value, "createName");
            return (Criteria) this;
        }

        public Criteria andCreateNameNotLike(String value) {
            addCriterion("create_name not like", value, "createName");
            return (Criteria) this;
        }

        public Criteria andCreateNameIn(List<String> values) {
            addCriterion("create_name in", values, "createName");
            return (Criteria) this;
        }

        public Criteria andCreateNameNotIn(List<String> values) {
            addCriterion("create_name not in", values, "createName");
            return (Criteria) this;
        }

        public Criteria andCreateNameBetween(String value1, String value2) {
            addCriterion("create_name between", value1, value2, "createName");
            return (Criteria) this;
        }

        public Criteria andCreateNameNotBetween(String value1, String value2) {
            addCriterion("create_name not between", value1, value2, "createName");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateNameIsNull() {
            addCriterion("update_name is null");
            return (Criteria) this;
        }

        public Criteria andUpdateNameIsNotNull() {
            addCriterion("update_name is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateNameEqualTo(String value) {
            addCriterion("update_name =", value, "updateName");
            return (Criteria) this;
        }

        public Criteria andUpdateNameNotEqualTo(String value) {
            addCriterion("update_name <>", value, "updateName");
            return (Criteria) this;
        }

        public Criteria andUpdateNameGreaterThan(String value) {
            addCriterion("update_name >", value, "updateName");
            return (Criteria) this;
        }

        public Criteria andUpdateNameGreaterThanOrEqualTo(String value) {
            addCriterion("update_name >=", value, "updateName");
            return (Criteria) this;
        }

        public Criteria andUpdateNameLessThan(String value) {
            addCriterion("update_name <", value, "updateName");
            return (Criteria) this;
        }

        public Criteria andUpdateNameLessThanOrEqualTo(String value) {
            addCriterion("update_name <=", value, "updateName");
            return (Criteria) this;
        }

        public Criteria andUpdateNameLike(String value) {
            addCriterion("update_name like", value, "updateName");
            return (Criteria) this;
        }

        public Criteria andUpdateNameNotLike(String value) {
            addCriterion("update_name not like", value, "updateName");
            return (Criteria) this;
        }

        public Criteria andUpdateNameIn(List<String> values) {
            addCriterion("update_name in", values, "updateName");
            return (Criteria) this;
        }

        public Criteria andUpdateNameNotIn(List<String> values) {
            addCriterion("update_name not in", values, "updateName");
            return (Criteria) this;
        }

        public Criteria andUpdateNameBetween(String value1, String value2) {
            addCriterion("update_name between", value1, value2, "updateName");
            return (Criteria) this;
        }

        public Criteria andUpdateNameNotBetween(String value1, String value2) {
            addCriterion("update_name not between", value1, value2, "updateName");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ws_order
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ws_order
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}