package com.sy.modules.dao.ws;

import com.sy.modules.common.MyBatisRepository;
import com.sy.modules.entity.ws.WsHuman;
import com.sy.modules.entity.ws.WsHumanExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
@MyBatisRepository
public interface WsHumanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ws_human
     *
     * @mbggenerated
     */
    int countByExample(WsHumanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ws_human
     *
     * @mbggenerated
     */
    int deleteByExample(WsHumanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ws_human
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long humanId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ws_human
     *
     * @mbggenerated
     */
    int insert(WsHuman record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ws_human
     *
     * @mbggenerated
     */
    int insertSelective(WsHuman record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ws_human
     *
     * @mbggenerated
     */
    List<WsHuman> selectByExampleWithRowbounds(WsHumanExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ws_human
     *
     * @mbggenerated
     */
    List<WsHuman> selectByExample(WsHumanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ws_human
     *
     * @mbggenerated
     */
    WsHuman selectByPrimaryKey(Long humanId);
    
    WsHuman selectByHumanAccount(String humanAccout);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ws_human
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") WsHuman record, @Param("example") WsHumanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ws_human
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") WsHuman record, @Param("example") WsHumanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ws_human
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(WsHuman record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ws_human
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(WsHuman record);
}